"""Add password column to users

Revision ID: 76e553394fc1
Revises: f7bb03e42cfe
Create Date: 2025-04-02 00:34:30.918487

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '76e553394fc1'
down_revision: Union[str, None] = 'f7bb03e42cfe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('exercice', 'value',
               existing_type=mysql.INTEGER(display_width=11),
               type_=sa.String(length=255),
               existing_nullable=True)
    op.alter_column('users', 'englishLevel',
               existing_type=mysql.ENUM('A1', 'A2', 'B1', 'B2', 'C1', 'C2'),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'englishLevel',
               existing_type=mysql.ENUM('A1', 'A2', 'B1', 'B2', 'C1', 'C2'),
               nullable=False)
    op.alter_column('exercice', 'value',
               existing_type=sa.String(length=255),
               type_=mysql.INTEGER(display_width=11),
               existing_nullable=True)
    # ### end Alembic commands ###
