"""add is_correct to options

Revision ID: 8a9cd703d56e
Revises: 62f090a4953f
Create Date: 2025-06-03 10:46:50.013614

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '8a9cd703d56e'
down_revision: Union[str, None] = '62f090a4953f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('exercises', 'type',
               existing_type=mysql.ENUM('grammar', 'listening', 'reading', 'vocabulary', 'writing'),
               type_=sa.Enum('listening', 'reading', 'grammar', 'writing', 'vocabulary', name='exercisetype'),
               nullable=False)
    op.add_column('options', sa.Column('is_correct', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('options', 'is_correct')
    op.alter_column('exercises', 'type',
               existing_type=sa.Enum('listening', 'reading', 'grammar', 'writing', 'vocabulary', name='exercisetype'),
               type_=mysql.ENUM('grammar', 'listening', 'reading', 'vocabulary', 'writing'),
               nullable=True)
    # ### end Alembic commands ###
