"""add option_id to user_answers

Revision ID: 8fc21b31a234
Revises: ba35bd7af8b7
Create Date: 2025-05-28 17:08:11.088354

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8fc21b31a234'
down_revision: Union[str, None] = 'ba35bd7af8b7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_answers', sa.Column('option_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'user_answers', 'options', ['option_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_answers', type_='foreignkey')
    op.drop_column('user_answers', 'option_id')
    # ### end Alembic commands ###
