"""add score to user_exercise_responses

Revision ID: 9d55e959b7b7
Revises: 354bcab37610
Create Date: 2025-06-04 11:50:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9d55e959b7b7'
down_revision: Union[str, None] = '354bcab37610'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_exercise_responses', sa.Column('score', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_exercise_responses', 'score')
    # ### end Alembic commands ###
