"""update_thematic_enum_values

Revision ID: bba4bb7b56ce
Revises: c40723a63efa
Create Date: 2025-06-23 14:28:06.957968

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'bba4bb7b56ce'
down_revision: Union[str, None] = 'c40723a63efa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_exercise_responses', 'completed_at')
    op.drop_column('user_exercise_responses', 'total_points')
    op.drop_column('user_exercise_responses', 'started_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_exercise_responses', sa.Column('started_at', mysql.DATETIME(), nullable=True))
    op.add_column('user_exercise_responses', sa.Column('total_points', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('user_exercise_responses', sa.Column('completed_at', mysql.DATETIME(), nullable=True))
    # ### end Alembic commands ###
