"""add is_valid to user_exercise_responses

Revision ID: c40723a63efa
Revises: 9d55e959b7b7
Create Date: 2025-06-04 11:55:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c40723a63efa'
down_revision: Union[str, None] = '9d55e959b7b7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_exercise_responses', sa.Column('is_valid', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_exercise_responses', 'is_valid')
    # ### end Alembic commands ###
