"""add submitted_at to user_exercise_responses

Revision ID: f047afcd9402
Revises: ba35bd7af8b7
Create Date: 2025-06-04 11:45:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f047afcd9402'
down_revision: Union[str, None] = 'ba35bd7af8b7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_exercise_responses', sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_exercise_responses', 'submitted_at')
    # ### end Alembic commands ###
