"""create exercise, question, option tables

Revision ID: f3b4562dbb3b
Revises: 1ab3bd2b49c8
Create Date: 2025-05-16 15:00:13.116717

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'f3b4562dbb3b'
down_revision: Union[str, None] = '1ab3bd2b49c8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('exercice',
        sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
        sa.Column('type', mysql.ENUM('LISTENING', 'WRITING', 'READING_COMPREHENTION', 'GRAMMAR'), nullable=False),
        sa.Column('response', mysql.VARCHAR(length=255), nullable=False),
        sa.Column('content', mysql.VARCHAR(length=255), nullable=False),
        sa.Column('valid', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False),
        sa.Column('value', mysql.VARCHAR(length=255), nullable=True),
        sa.Column('level', mysql.ENUM('A1', 'A2', 'B1', 'B2', 'C1', 'C2'), nullable=False),
        sa.PrimaryKeyConstraint('id'),
        mysql_collate='utf8mb4_0900_ai_ci',
        mysql_default_charset='utf8mb4',
        mysql_engine='InnoDB'
    )
    op.create_index('ix_exercice_id', 'exercice', ['id'], unique=False)
    op.create_table('content',
        sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
        sa.Column('thematic', mysql.ENUM('ALGO'), nullable=False),
        sa.Column('link', mysql.VARCHAR(length=255), nullable=False),
        sa.Column('title', mysql.VARCHAR(length=255), nullable=False),
        sa.Column('img', mysql.VARCHAR(length=255), nullable=False),
        sa.PrimaryKeyConstraint('id'),
        mysql_collate='utf8mb4_0900_ai_ci',
        mysql_default_charset='utf8mb4',
        mysql_engine='InnoDB'
    )
    op.create_index('ix_content_link', 'content', ['link'], unique=True)
    op.create_index('ix_content_id', 'content', ['id'], unique=False)
    op.create_table('users',
        sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
        sa.Column('name', mysql.VARCHAR(length=255), nullable=False),
        sa.Column('email', mysql.VARCHAR(length=255), nullable=False),
        sa.Column('password', mysql.VARCHAR(length=255), nullable=False),
        sa.Column('points', mysql.INTEGER(), autoincrement=False, nullable=True),
        sa.Column('isAdmin', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False),
        sa.Column('englishLevel', mysql.ENUM('A1', 'A2', 'B1', 'B2', 'C1', 'C2'), nullable=True),
        sa.PrimaryKeyConstraint('id'),
        mysql_collate='utf8mb4_0900_ai_ci',
        mysql_default_charset='utf8mb4',
        mysql_engine='InnoDB'
    )
    op.create_index('ix_users_id', 'users', ['id'], unique=False)
    op.create_index('ix_users_email', 'users', ['email'], unique=True)
    # ### end Alembic commands ###

def downgrade() -> None:
    """Downgrade schema."""
    op.drop_index('ix_users_email', table_name='users')
    op.drop_index('ix_users_id', table_name='users')
    op.drop_table('users')
    op.drop_index('ix_content_id', table_name='content')
    op.drop_index('ix_content_link', table_name='content')
    op.drop_table('content')
    op.drop_index('ix_exercice_id', table_name='exercice')
    op.drop_table('exercice')
