"""creacion de tablas

Revision ID: f7bb03e42cfe
Revises: 0635d41ab752
Create Date: 2025-04-01 20:08:00.003866

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f7bb03e42cfe'
down_revision: Union[str, None] = '0635d41ab752'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(255), nullable=False),
    sa.Column('email', sa.String(255), nullable=False),
    sa.Column('hashed_password', sa.String(255), nullable=False),
    sa.Column('points', sa.Integer(), nullable=True),
    sa.Column('isAdmin', sa.Boolean(), nullable=False),
    sa.Column('englishLevel', sa.Enum('A1', 'A2', 'B1', 'B2', 'C1', 'C2', name='english_level'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_table('exercice',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type', sa.Enum('LISTENING', 'WRITING', 'READING_COMPREHENTION', 'GRAMMAR', name='exercice_type'), nullable=False),
    sa.Column('response', sa.String(255), nullable=False),
    sa.Column('content', sa.String(255), nullable=False),
    sa.Column('valid', sa.Boolean(), nullable=False),
    sa.Column('value', sa.Integer(), nullable=True),
    sa.Column('level', sa.Enum('A1', 'A2', 'B1', 'B2', 'C1', 'C2', name='english_level'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_exercice_id'), 'exercice', ['id'], unique=False)
    op.create_index(op.f('ix_exercice_response'), 'exercice', ['response'], unique=True)
    op.create_table('content',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('thematic', sa.Enum('ALGO', name='thematic'), nullable=False),
    sa.Column('link', sa.String(255), nullable=False),
    sa.Column('title', sa.String(255), nullable=False),
    sa.Column('img', sa.String(255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_content_id'), 'content', ['id'], unique=False)
    op.create_index(op.f('ix_content_link'), 'content', ['link'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_content_link'), table_name='content')
    op.drop_index(op.f('ix_content_id'), table_name='content')
    op.drop_table('content')
    op.drop_index(op.f('ix_exercice_response'), table_name='exercice')
    op.drop_index(op.f('ix_exercice_id'), table_name='exercice')
    op.drop_table('exercice')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
